apiVersion: apps/v1
kind: Deployment
metadata: { name: web, namespace: apps }
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      automountServiceAccountToken: false      # don't mount SA token unless needed
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports: [{ containerPort: 8080 }]
          securityContext:
            allowPrivilegeEscalation: false      # blocks setuid escalation
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - { name: cache, mountPath: /var/cache/nginx }
            - { name: run, mountPath: /var/run }
      volumes:
        - { name: cache, emptyDir: {} }
        - { name: run, emptyDir: {} }
