apiVersion: v1
kind: ResourceQuota
metadata: { name: tenant-a-quota, namespace: tenant-a }
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    count/services.loadbalancers: "2"
    count/secrets: "50"
    persistentvolumeclaims: "20"
